name = "gleam_mist_std"
version = "0.1.0"
gleam = ">= 1.4.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
